---
- name: clone the repo
  git:
    repo: "{{clone_url}}"
    dest: ~/workspace
    depth: 1
    version: "{{branch}}"

- name: set to devinfra
  lineinfile:
    dest: /etc/gu/install_vars
    regexp: '^STAGE='
    line: 'STAGE=DEVINFRA'
    create: yes
  become: true

- name: override location of capi
  lineinfile:
    dest: /home/ubuntu/.gu/frontend.conf
    regexp: '^content.api.host.*'
    line: 'content.api.host = "http://localhost:9001"'
    create: yes

- name: preinstall nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

- name: preinstall nvm part II
  shell: . ~/.nvm/nvm.sh; nvm install
  args:
    chdir: ~/workspace
    executable: /bin/bash

- name: run setup.py
  command: ~/workspace/setup.sh
  args:
    chdir: ~/workspace/

- name: sbt compile
  command: ~/workspace/sbt "project article" "compile"
  args:
    chdir: ~/workspace

- name: run the article project
  command: screen -S trousers-build -d -m ~/workspace/sbt "project article" "run"
  args:
    chdir: ~/workspace

- name: wait for the application to become available
  wait_for:
    port: 9000
    delay: 7

- name: check that localhost is returning 200 for an article
  uri:
      url: http://localhost:9000/category/day/mon/year/slug

- name: kill the application
  command: screen -S trousers-build -X quit
