---

- name: wipe the artifacts directory
  file:
    path: /home/ubuntu/artifacts
    state: absent

- name: create the artifacts directory
  file:
    path: /home/ubuntu/artifacts
    state: directory

- name: clone the repo
  git:
    repo: "{{clone_url}}"
    dest: ~/workspace
    depth: 1
    force: yes
    version: "{{branch}}"

- name: set to devinfra
  lineinfile:
    dest: /etc/gu/install_vars
    regexp: '^STAGE='
    line: 'STAGE=PROD'
    create: yes
  become: true

- name: override location of capi
  lineinfile:
    dest: /home/ubuntu/.gu/frontend.conf
    regexp: '^devOverrides.*'
    line: 'devOverrides { content.api.host = "http://localhost:9001" }'
    create: yes

- name: preinstall nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

- name: preinstall nvm part II
  shell: . ~/.nvm/nvm.sh; nvm install
  args:
    chdir: ~/workspace
    executable: /bin/bash

- name: run setup.py
  command: ~/workspace/setup.sh
  args:
    chdir: ~/workspace/

- name: sbt compile
  command: ~/workspace/sbt "project article" "compile"
  args:
    chdir: ~/workspace

- block:
    
  - name: run the article project
    command: screen -S trousers-build -d -m ~/workspace/sbt "project article" "run"
    args:
      chdir: ~/workspace

  - name: wait for the application to become available
    wait_for:
      port: 9000
      delay: 7

  - name: check that localhost is returning 200 for an article
    uri:
      url: http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism

  - name: run screenshots
    shell: . ~/.nvm/nvm.sh; nvm use; make screenshots
    args:
      chdir: ~/workspace
      executable: /bin/bash

  - name: copy screenshots into artifacts
    shell: cp -r screenshots ~/artifacts/
    args:
      chdir: ~/workspace/

  - name: clone down the webpagetest tool
    git:
      repo: "https://github.com/michaelwmcnamara/single-page-performance-tester.git"
      dest: ~/perftester
      depth: 1
      force: yes

  - name: run webpage tests
    shell: bash runme.sh $(curl http://169.254.169.254/latest/meta-data/public-hostname):9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism /home/ubuntu/artifacts
    args:
      chdir: /home/ubuntu/perftester

  - name: run exception checker
    shell: bash /home/ubuntu/prbuilds/trousers/builtins/exceptions.js http://localhost:9000/books/2014/may/21/guardian-journalists-jonathan-freedland-ghaith-abdul-ahad-win-orwell-prize-journalism > /home/ubuntu/artifacts/thrown-exceptions.txt
    
  always:
    
  - name: kill the application
    command: screen -S trousers-build -X quit
