AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    48ef8c3d-0402-4675-95b5-f2721324af4b:
      source:
        id: 908bc72d-f53b-4b6a-8e15-e473e5d4b771
      target:
        id: 906ac66e-0e40-43d5-b624-c65a6bf7f682
      z: 1
    2c1f9dbe-4715-485c-91a8-b62b954ca01c:
      size:
        width: 60
        height: 60
      position:
        x: 400
        'y': 60
      z: 0
      embeds: []
    0972be32-ed35-4c6b-b518-92aeb256270a:
      source:
        id: 73b9d7cd-0690-4832-a14e-b10a6dfee61a
      target:
        id: 8486dddf-5f2c-413f-8dfa-778adad817f6
      z: 11
    a6bfb15d-e69a-4cb7-8035-12203ff9f993:
      source:
        id: 8486dddf-5f2c-413f-8dfa-778adad817f6
      target:
        id: 2c1f9dbe-4715-485c-91a8-b62b954ca01c
      z: 12
    0c2e4049-01a4-4795-8388-7a945739bed0:
      source:
        id: 908bc72d-f53b-4b6a-8e15-e473e5d4b771
      target:
        id: 2c1f9dbe-4715-485c-91a8-b62b954ca01c
      z: 13
    a80330d0-bd4f-4c19-a0e5-163a17422c0b:
      size:
        width: 60
        height: 60
      position:
        x: 290
        'y': -50
      z: 0
      embeds: []
      ismemberof:
        - c1b0042c-39b9-4a58-b120-1e1fca75ce59
    f93d1cb1-b3e9-44a7-aedc-2cbf24df09b4:
      source:
        id: 908bc72d-f53b-4b6a-8e15-e473e5d4b771
      target:
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
      z: 14
    69ab18ae-44f6-473d-a939-9b97bff5e388:
      size:
        width: 60
        height: 60
      position:
        x: 290
        'y': 60
      z: 0
      embeds: []
      isconnectedto:
        - 25b25e6e-bfae-44ed-9e5d-ad50d1db709e
      isassociatedwith:
        - a80330d0-bd4f-4c19-a0e5-163a17422c0b
      dependson:
        - 2c1f9dbe-4715-485c-91a8-b62b954ca01c
    33b44414-38c1-4691-997b-b97c5826c563:
      source:
        id: 906ac66e-0e40-43d5-b624-c65a6bf7f682
      target:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      z: 11
    e3438090-0837-4b4e-92f7-f6efbde37683:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: 2c1f9dbe-4715-485c-91a8-b62b954ca01c
      z: 12
    a392ec9e-74b2-4552-a008-80a5736619e5:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
      z: 13
    48b79039-9b1a-4728-a1f7-ac3706b08235:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: 906ac66e-0e40-43d5-b624-c65a6bf7f682
      z: 11
    b7c4a649-7612-40f7-9ba7-f469cb6ba1fc:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
      z: 12
    d7b77ba1-be08-4fd1-84de-d95ff6ae06d2:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
      z: 11
    1631f8a6-46f6-4365-a95c-11cbd3f0d280:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: 906ac66e-0e40-43d5-b624-c65a6bf7f682
      z: 12
    c1b0042c-39b9-4a58-b120-1e1fca75ce59:
      size:
        width: 60
        height: 60
      position:
        x: 400
        'y': -50
      z: 0
      embeds: []
    912a314a-80b5-440b-8f39-3fa26130f34b:
      source:
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
      target:
        id: c1b0042c-39b9-4a58-b120-1e1fca75ce59
      z: 11
    25b25e6e-bfae-44ed-9e5d-ad50d1db709e:
      size:
        width: 60
        height: 60
      position:
        x: 170
        'y': 60
      z: 0
      embeds: []
    c5ccd025-3270-4f44-99fe-4e8f8132b632:
      source:
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
      target:
        id: 25b25e6e-bfae-44ed-9e5d-ad50d1db709e
      z: 11
Resources:
  SQSQY9XB:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Ref QueueNameParameter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2c1f9dbe-4715-485c-91a8-b62b954ca01c
  ASLC1HDK6:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !Ref AMIParameter
      InstanceType: t2.medium
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref InstanceProfileParameter
      KeyName: !Ref KeyNameParameter
      SecurityGroups:
        - !Ref EC2SG9TSH
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - >
              git clone https://github.com/guardian/prbuilds.git
              /home/ubuntu/prbuilds
            - export GH_NAME=
            - !Ref GitHubNameParameter
            - |+

            - export GH_TOKEN=
            - !Ref GitHubKeyParameter
            - |+

            - export QUEUE_NAME=
            - !Ref QueueNameParameter
            - |+

            - |
              cd /home/ubuntu/prbuilds
            - |
              ./install.sh
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a80330d0-bd4f-4c19-a0e5-163a17422c0b
  ASASGTGZ9:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones:
        - eu-west-1a
      VPCZoneIdentifier: !Ref SubnetsParameter
      HealthCheckType: ELB
      HealthCheckGracePeriod: '300'
      MinSize: '1'
      MaxSize: !Ref CapacityParameter
      DesiredCapacity: !Ref CapacityParameter
      Tags:
        - Key: App
          Value: PRBuilds
          PropagateAtLaunch: true
      LaunchConfigurationName: !Ref ASLC1HDK6
      LoadBalancerNames:
        - !Ref ELBLB1FOS4
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 69ab18ae-44f6-473d-a939-9b97bff5e388
    DependsOn:
      - SQSQY9XB
  EC2SG9TSH:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: PRBuilds instance security group
      VpcId: !Ref VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9002
          ToPort: 9002
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c1b0042c-39b9-4a58-b120-1e1fca75ce59
  ELBLB1FOS4:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Listeners:
        - { LoadBalancerPort: 80, InstancePort: 9002, Protocol: HTTP }
      CrossZone: true
      HealthCheck:
        Target: 'HTTP:9002/healthcheck'
        HealthyThreshold: 2
        UnhealthyThreshold: 10
        Interval: 30
        Timeout: 10
      Subnets: !Ref SubnetsParameter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 25b25e6e-bfae-44ed-9e5d-ad50d1db709e
Parameters:
  AMIParameter:
    Description: AMI to use
    Type: String
  SubnetsParameter:
    Description: VPC Subnet
    Type: 'List<AWS::EC2::Subnet::Id>'
  VpcIdParameter:
    Description: VPC Id
    Type: 'AWS::EC2::VPC::Id'
  KeyNameParameter:
    Description: An ssh keypair to put on the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  CapacityParameter:
    Type: String
    Default: '1'
    Description: Scaling group size
  InstanceProfileParameter:
    Type: String
    Default: TrousersInstanceProfile
    Description: Instance profile to use (must have SQS and S3 permissions)
  QueueNameParameter:
    Type: String
    Default: trousers_in
    Description: Queue name
  GitHubNameParameter:
    Type: String
    Default: PRBuilds
    Description: GitHub account name to use
  GitHubKeyParameter:
    Type: String
    Default: ''
    Description: GitHub key to use
