---
- hosts: localhost
  environment:
    AWS_PROFILE: frontend
  tasks:
    
    - name: launch an instance
      ec2:
        key_name: matthew-walls
        instance_type: t2.medium
        image: ami-d75f22a4
        wait: yes
        count: 1
        vpc_subnet_id: subnet-c682e7b0
        assign_public_ip: yes
        group_id: sg-d7827eb1
        region: eu-west-1
        instance_tags:
           Lifetime: Temporary
      register: ec2
    
    - name: wait for ssh to become available
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: add the host
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: pickles
      with_items: "{{ ec2.instances }}"

- hosts: pickles
  remote_user: ubuntu    
  roles:
    - article
    
