---
- hosts: localhost
  tasks:
    
    - name: launch an instance
      ec2:
        key_name: matthew-walls
        instance_type: t2.medium
        image: ami-d75f22a4
        wait: yes
        count: 1
        vpc_subnet_id: subnet-c682e7b0
        assign_public_ip: yes
        group_id: sg-d7827eb1
        region: eu-west-1
        instance_tags:
           Lifetime: Temporary
      register: ec2
    
    - name: wait for ssh to become available
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: add the host
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: pickles
      with_items: "{{ ec2.instances }}"

- hosts: pickles
  remote_user: ubuntu
    
  environment:
    AWS_USER: "{{aws_user}}"
    AWS_KEY: "{{aws_key}}"
    GH_NAME: "{{gh_name}}"
    GH_TOKEN: "{{gh_token}}"

  tasks:
    - name: "Copy over the software"
      copy:
        src=./trousers
        dest=~/

    - name: install pip
      apt:
        name: python-pip
        update_cache: yes
      become: true

    - name: install build-essential
      apt:
        name: build-essential
        update_cache: yes
      become: true

    - name: install python dev
      apt:
        name: python-dev
        update_cache: yes
      become: true

    - name: install libffi
      apt:
        name: libffi-dev
        update_cache: yes
      become: true

    - name: install libssl
      apt:
        name: libssl-dev
        update_cache: yes
      become: true    
    
    - name: install python libs
      command: pip install -r /home/ubuntu/trousers/requirements.txt
      args:
        chdir: /home/ubuntu/trousers
      become: true

    - name: run ether
      command: screen -d -m python ether.py
      args:
        chdir: /home/ubuntu/trousers
        
    - name: run trousers
      command: screen -d -m python trousers.py
      args:
        chdir: /home/ubuntu/trousers
