setup:
    ansible: build.playbook.yml
checks:
    screenshots: http://localhost:9000/uk
    exceptions: http://localhost:9000/uk
teardown:
    ansible: cleanup.playbook.yml
reporting:
    github: github_comment.template
