setup:
    ansible: build.playbook.yml
checks:
    screenshots:
      url: http://localhost:9000/uk
    exceptions:
      url: http://localhost:9000/uk
teardown:
    ansible: cleanup.playbook.yml
reporting:
    github: github_comment.template
